
image:
  repository: otomato/goofys
  pullPolicy: IfNotPresent
  # Overrides the image tag whose default is the chart appVersion.
  tag: ""

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

serviceAccount:
  # Specifies whether a service account should be created
  create: true
  name: s3-mounter

bucketName: eksbuckets3
iamRoleARN: arn:aws:iam::363436838884:policy/kubernetes-s3-access
mountPath: /var/s3
hostPath: /mnt/s3data

